name: Setup the repository
description: Install Python and the dependencies
runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true
        version: "0.4.20"
    - run: uv python install 3.10
      shell: bash
    - run: un sync --locked
      shell: bash
