name: Setup the repository
description: Install Python and the dependencies
runs:
  using: "composite"
  steps:
    - uses: ./.github/setup-uv
      with:
        enable-cache: true
    - run: uv python install 3.10.15
      shell: bash
    - run: uv sync --locked
      shell: bash
