name: Setup the repository
description: Set up Python, install Poetry and the dependencies
runs:
  using: "composite"
  steps:
    - run: pipx install poetry==1.3.1
      shell: bash
    - uses: actions/setup-python@v4
      with:
        cache: poetry
        python-version: "3.8"
    - run: poetry install --no-interaction
      shell: bash
