[tool.poetry]
authors = ["Thibault Derousseaux <tibdex@gmail.com>"]
description = "Convert a Pure-Python Wheel to a noarch Conda package"
keywords = ["conda", "conda-package", "python-wheel", "wheel"]
license = "MIT"
name = "python-wheel-to-conda-package"
packages = [{include = "python_wheel_to_conda_package"}]
readme = "README.md"
repository = "https://github.com/tibdex/python-wheel-to-conda-package"
version = "0.2.0"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.group.dev.dependencies]
black = "*"
isort = "*"
mypy = "*"
pandas = "*"
pandas-stubs = "*"
pytest = "*"

[tool.poetry.scripts]
python-wheel-to-conda-package = 'python_wheel_to_conda_package.__main__:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
combine_as_imports = "True"

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = [
  "setuptools"
]
ignore_missing_imports = true
