name: Publish
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv build --wheel
      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: python-wheel
          path: dist/*.whl

  publish:
    environment: publish
    name: Publish
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      # Required for trusted publishing.
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist
      - run: ls -la dist
      - run: uv publish
