name: Test
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: poetry lock --check
      - run: poetry run black --check .
      - run: poetry run ruff check .
      - run: poetry run mypy --show-error-codes --package python_wheel_to_conda_package --package tests
      - uses: conda-incubator/setup-miniconda@v2
        with:
          conda-build-version: "3.23.3"
      - run: poetry run pytest --capture=no
