name: Test
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: poetry run black --check .
      - run: poetry run isort --check --gitignore .
      - uses: conda-incubator/setup-miniconda@v2
        with:
          conda-build-version: "3.23.3"
      - run: poetry run pytest --capture=no
