name: Test
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv run ruff format --check
      - run: uv run ruff check
      - run: uv run mypy
      - uses: conda-incubator/setup-miniconda@v3
        with:
          conda-build-version: "24.7.1"
      - run: uv run pytest --capture=no
      - run: uv build --wheel
      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: python-wheel
          path: dist/*.whl
