name: Test
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: poetry check --lock
      - run: poetry run ruff format --check .
      - run: poetry run ruff check .
      - run: poetry run mypy --show-error-codes --package python_wheel_to_conda_package --package tests
      - uses: conda-incubator/setup-miniconda@v2
        with:
          conda-build-version: "3.27.0"
      - run: poetry run pytest --capture=no
