name: Test
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv run ruff format --check
      - run: uv run ruff check
      - run: uv run mypy
      - uses: conda-incubator/setup-miniconda@v3
        with:
          conda-build-version: "24.7.1"
      - run: uv run pytest --capture=no
